<?php
/*
General configuration file
Automatically generated by Neopibox using the admin panel
*/

$maintenance = 0;
$titleMaintenance = "Site en Maintenance";
$contentMaintenance = "<p>Le site est actuellement en maintenance, veuillez patientez jusqu&#39;&agrave; la r&eacute;ouverture du site.</p>
";
$contentAboutMe = "<p>Bonjour ! Mon pseudo est Neopibox, mais je suis plus connu IRL sous le nom de Evan. J&#39;ai 17 ans, et je d&eacute;veloppe depuis 7 ans environ. En plus de cela, je fais de l&#39;&eacute;lectronique &agrave; mes heures perdues.</p>

<p>Plus tard, je compte travailler dans l&#39;informatique et/ou l&#39;&eacute;lectronique. J&#39;aimerais faire du developpement sur des syst&egrave;mes embarqu&eacute;s, mais avec le but ultime de travailler dans le domaine de l&#39;a&eacute;rospatiale. En attendant, je passe un bac S-SVT sp&eacute;cialit&eacute; ISN.</p>

<p>Sur ce site, je compte pr&eacute;senter&nbsp;mes projets sur lesquels je travaille. Par exemple, mes projets &eacute;lectronqiues, mes programmes informatiques, mes sites webs,&nbsp;</p>

<p>Mais aussi, publier&nbsp;des avis personnels sur l&#39;actualit&eacute;, des petits tests, des outils et des astuces de developpement, bref, tout ce qui me passe par la t&ecirc;te.</p>

<p>J&#39;esp&egrave;re que vous aimerez&nbsp;ce site que j&#39;appr&eacute;cie programmer.</p>

<p>Neopibox</p>
";
