<?php

function writeConfiguration($boolMaintenance, $title, $contentMaintenance, $contentAboutMe)
{
		// Trying to open 
	if(!$file = fopen('config/general.php', 'w+'))
	{
		require_once('view/admin/configuration.php');
		exit();
	}

	// Header
	fseek($file, 0);
	fputs($file, "<?php\r\n");
	fputs($file, "/*\r\n");
	fputs($file, "General configuration file\r\n");
	fputs($file, "Automatically generated by Neopibox using the admin panel\r\n");
	fputs($file, "*/\r\n");
	fputs($file, "\r\n");

	// Maintenance
	fputs($file, '$maintenance = ');
	fputs($file, "$boolMaintenance;\r\n");
	fputs($file, '$titleMaintenance = "');
	fputs($file, "$title\";\r\n");
	fputs($file, '$contentMaintenance = "');
	fputs($file, "$contentMaintenance\";\r\n");

	// About Me
	fputs($file, '$contentAboutMe = "');
	fputs($file, "$contentAboutMe\";\r\n");

	fclose($file);
}